### ISSUE TITLE
Create new label; PyPI link is not functional

### ISSUE THREAD

**Issue by CrazyPython** [OpenCageData/python-opencage-geocoder#11]
Link from [PyPI](https://codeload.github.com/OpenCageData/python-opencage-geocoder/legacy.tar.gz/1.1.2) gets you to:
```
Not Found
```

**Comment by mtmail** [comment]
Oh, that's embarrassing. I wonder why the tool let me upload it with obvious missing files... *)

Anyway, version 1.1.3 fixes this and I updated my release documentation https://pypi.python.org/pypi/opencage/1.1.3

Thank a lot for pushing us! Let me know if anything else looks off. 

*) root cause was probably an error with hard-links inside my virtual machine http://bugs.python.org/issue8876

**Comment by CrazyPython** [comment]
Yup; it works now. Pip has successfully installed it.
