### ISSUE TITLE
floatify_latlng(input_value) crashing on DMS coordinates

### ISSUE THREAD

**Issue by JimHagan** [OpenCageData/python-opencage-geocoder#6]
On line 176 of geocoder.py this line will crash.  Need to handle the situation where the lng an lat elements are not convertable to float.

**Comment by JimHagan** [comment]
Here is how I patched it although it was just a quick fix...

def float_if_float(float_string):
    try:
        float_val = float(float_string)
        return float_val
    except ValueError:
        return float_string


Later on (was line 176) call it like so...

            return {'lat': float_if_float(input_value["lat"]), 'lng': float_if_float(input_value["lng"])}

**Comment by mtmail** [comment]
Thanks a lot! I suspected some weirdness in JSON utf8 encoding but it's the (quite custom) logic of identifying floats. Since the module was written we improved the JSON output of our API so in a lot of cases the logic is no longer needed.

Note that you added your API key in the pull request. Somebody might find and use it and hit the daily quota.
